// Sandbox: a full copy of the app on a throwaway local database, so editing
// never touches the live roster.
//
// The problem it solves: this repo's `.env` points DATABASE_URL at the
// production Neon branch. `npm run dev`, `npm run db:seed`, and every test that
// takes a database therefore run against real members. There was no safe place
// to click around.
//
//   npm run sandbox:up      start Postgres, migrate, seed fake people
//   npm run sandbox         run the app against it on :3011
//   npm run sandbox:reset   wipe and re-seed
//   npm run sandbox:down    stop and delete the container
//   npm run sandbox:psql    a psql shell on the sandbox database
//
// Nothing here can reach production: the sandbox refuses to run unless the
// database URL resolves to localhost, and it blanks every outbound provider key
// so a stray click cannot email or text a real person.
import { spawn, spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const ENV_FILE = join(ROOT, ".env.sandbox");
const CONTAINER = "mutuals-sandbox-pg";
const PORT = 5433; // not 5432, so it cannot collide with a local Postgres
// The usual dev port, because the sandbox is now what `npm run dev` means.
// Pointing a dev server at the live roster is `npm run dev:live`, on 3019.
const APP_PORT = Number(process.env.SANDBOX_PORT) || 3009;
const DB_URL = `postgresql://postgres@127.0.0.1:${PORT}/mutuals_sandbox?schema=meetcute`;

// Every provider that can reach the outside world, blanked. An empty string is
// deliberate rather than unset: the app's own code checks for a truthy key, and
// an unset variable would fall through to whatever is in .env.
const OUTBOUND_KEYS = [
  "RESEND_API_KEY",
  "RESEND_WEBHOOK_SECRET",
  "TWILIO_ACCOUNT_SID",
  "TWILIO_AUTH_TOKEN",
  "TWILIO_FROM",
  "PRELUDE_API_KEY",
  "BLOB_READ_WRITE_TOKEN",
  "SENTRY_DSN",
  "NEXT_PUBLIC_SENTRY_DSN",
  "SENTRY_AUTH_TOKEN",
  "REDIS_URL",
];

function sh(cmd: string, args: string[], opts: { quiet?: boolean; env?: NodeJS.ProcessEnv } = {}) {
  const r = spawnSync(cmd, args, {
    cwd: ROOT,
    encoding: "utf8",
    stdio: opts.quiet ? "pipe" : "inherit",
    env: opts.env ?? process.env,
  });
  return { ok: r.status === 0, out: `${r.stdout ?? ""}${r.stderr ?? ""}`.trim() };
}

function die(msg: string): never {
  console.error(`\nsandbox: ${msg}\n`);
  process.exit(1);
}

/** The one safety rail that matters: never act on anything but localhost. */
function assertLocal(url: string) {
  let host: string;
  try {
    host = new URL(url).hostname;
  } catch {
    die(`could not parse the sandbox DATABASE_URL`);
  }
  if (!["127.0.0.1", "localhost", "::1"].includes(host)) {
    die(`refusing to run: the sandbox database must be local, got host "${host}"`);
  }
}

function writeEnvFile() {
  const lines = [
    "# Generated by `npm run sandbox:up`. Local only, never committed.",
    "# Every outbound provider is blank on purpose: the sandbox must not be",
    "# able to email, text, or page a real person.",
    `MUTUALS_ENV=sandbox`,
    `DATABASE_URL=${DB_URL}`,
    `DIRECT_URL=${DB_URL}`,
    `NEXT_PUBLIC_APP_URL=http://127.0.0.1:${APP_PORT}`,
    `MUTUALS_DEMO_LOGIN=1`,
    `SESSION_SECRET=sandbox-only-not-a-secret-0000000000000000`,
    ...OUTBOUND_KEYS.map((k) => `${k}=`),
    "",
    "# The co-pilot still runs for real against the free NVIDIA tier. Drop the",
    "# key in here if you want live tool-calling in the sandbox.",
    `NVIDIA_API_KEY=${process.env.NVIDIA_API_KEY ?? ""}`,
  ];
  writeFileSync(ENV_FILE, lines.join("\n") + "\n");
}

function sandboxEnv(): NodeJS.ProcessEnv {
  if (!existsSync(ENV_FILE)) die("no .env.sandbox yet. Run `npm run sandbox:up` first.");
  const env: NodeJS.ProcessEnv = { ...process.env };
  for (const line of readFileSync(ENV_FILE, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 1) continue;
    // Overwrite, unlike @next/env: the whole point is to beat the .env that
    // points at production.
    env[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  assertLocal(env.DATABASE_URL ?? "");
  return env;
}

function containerState(): "running" | "stopped" | "absent" {
  const r = sh("docker", ["inspect", "-f", "{{.State.Running}}", CONTAINER], { quiet: true });
  if (!r.ok) return "absent";
  return r.out.trim() === "true" ? "running" : "stopped";
}

async function waitForPostgres(timeoutMs = 60_000) {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    if (sh("docker", ["exec", CONTAINER, "pg_isready", "-U", "postgres"], { quiet: true }).ok) return;
    await new Promise((r) => setTimeout(r, 750));
  }
  die("Postgres did not come up in 60s. Is Docker running?");
}

async function up() {
  if (!sh("docker", ["info"], { quiet: true }).ok) die("Docker is not running. Start Docker Desktop and try again.");

  const state = containerState();
  if (state === "absent") {
    console.log(`sandbox: creating ${CONTAINER} on port ${PORT}`);
    const r = sh("docker", [
      "run", "-d",
      "--name", CONTAINER,
      "-e", "POSTGRES_HOST_AUTH_METHOD=trust",
      "-e", "POSTGRES_DB=mutuals_sandbox",
      "-p", `${PORT}:5432`,
      "postgres:16",
    ], { quiet: true });
    if (!r.ok) die(`could not start Postgres:\n${r.out}`);
  } else if (state === "stopped") {
    console.log(`sandbox: restarting ${CONTAINER}`);
    sh("docker", ["start", CONTAINER], { quiet: true });
  } else {
    console.log(`sandbox: ${CONTAINER} is already running`);
  }

  await waitForPostgres();
  writeEnvFile();
  const env = sandboxEnv();

  console.log("sandbox: applying migrations");
  if (!sh("npx", ["prisma", "migrate", "deploy"], { env }).ok) die("migrations failed");

  console.log("sandbox: seeding");
  if (!sh("npx", ["tsx", "scripts/seed.ts"], { env }).ok) {
    console.warn("sandbox: seed script failed; the database is empty but usable");
  }

  console.log(
    [
      "",
      "sandbox is up.",
      `  database  ${DB_URL}`,
      `  app       npm run sandbox   ->  http://127.0.0.1:${APP_PORT}`,
      "  email/SMS disabled, demo login on, production untouched",
      "",
    ].join("\n")
  );
}

/**
 * Next 16 keeps one background dev server per project directory and silently
 * reuses it, environment and all. Starting the sandbox next to a dev server
 * that is already pointed at production would therefore attach to the
 * production one and report success. Stop it first, so the env below is the env
 * that actually runs.
 */
function stopExistingDevServer() {
  // ps, not pgrep: pgrep has under-reported live processes on this machine.
  const listing = sh("ps", ["ax", "-o", "pid=,command="], { quiet: true });
  const pids = listing.out
    .split("\n")
    .filter((l) => /next-server|next dev|\/next\b.*dev/.test(l))
    .map((l) => Number(l.trim().split(/\s+/)[0]))
    .filter((n) => Number.isFinite(n) && n !== process.pid);
  if (!pids.length) return;
  console.log(`sandbox: stopping ${pids.length} running dev server process(es) so the sandbox env takes effect`);
  for (const pid of pids) {
    try {
      process.kill(pid, "SIGTERM");
    } catch {
      /* already gone */
    }
  }
}

function dev() {
  const env = sandboxEnv();
  stopExistingDevServer();
  console.log(`sandbox: next dev on http://127.0.0.1:${APP_PORT} against the local database`);
  const child = spawn("npx", ["next", "dev", "-p", String(APP_PORT)], { cwd: ROOT, stdio: "inherit", env });
  child.on("exit", (code) => process.exit(code ?? 0));
}

async function reset() {
  const env = sandboxEnv();
  console.log("sandbox: dropping and recreating the schema");
  if (!sh("npx", ["prisma", "migrate", "reset", "--force", "--skip-generate"], { env }).ok) die("reset failed");
  sh("npx", ["tsx", "scripts/seed.ts"], { env });
  console.log("sandbox: reset");
}

function down() {
  sh("docker", ["rm", "-f", CONTAINER], { quiet: true });
  console.log("sandbox: container removed. `npm run sandbox:up` brings it back.");
}

function psql() {
  const r = spawnSync("docker", ["exec", "-it", CONTAINER, "psql", "-U", "postgres", "-d", "mutuals_sandbox"], {
    stdio: "inherit",
  });
  process.exit(r.status ?? 0);
}

const command = process.argv[2] ?? "dev";
const commands: Record<string, () => void | Promise<void>> = { up, dev, reset, down, psql };
if (!commands[command]) die(`unknown command "${command}". One of: ${Object.keys(commands).join(", ")}`);
Promise.resolve(commands[command]()).catch((e) => die((e as Error).message));
